name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: orbisdev/orbisdev-sdkvanilla:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apk add build-base ncurses-dev
    - name: Compile orbisdev-utils
      run: |
        make clean all install
